### ISSUE TITLE
Twitch OIDC returns scope in token as array

### ISSUE THREAD

**Issue by andreypopp** [ulrikstrid/ocaml-oidc#11]
According to https://datatracker.ietf.org/doc/html/rfc6749#section-5.1 the `scope` in token response should be a space separated list of scopes which ocaml-oidc expects.

Twitch OIDC implementation returns `"scope": ["openid"]` (also documented [here](https://dev.twitch.tv/docs/authentication/getting-tokens-oidc#oidc-authorization-code-flow)).

I'm not sure what ocaml-oidc should do here — ignore, fail (like it does now) or try to parse an array — but just creating the issue to discuss and at least to document this behaviour.

**Comment by ulrikstrid** [comment]
I think we should try to be lenient with parsing of things like this since we (apparently) can't trust that provider implementations follow the spec.
If you want to open a PR to try parsing it as an array if it fails in the first case I would be happy to merge it.

Btw, from your link it looks like they should be following the spec
> Space-separated list of [scopes](https://dev.twitch.tv/docs/authentication/#scopes). This must include the openid scope.

**Comment by andreypopp** [comment]
> Btw, from your link it looks like they should be following the spec

If you scroll down till the example response you can see 
```
"scope": ["viewing_activity_read"]
```
which amusingly contradicts the doc they have written themselves above.
